# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Delete all
FormSlotHistory.delete_all
TitleHistory.delete_all
LineManager.delete_all
Comment.delete_all
FormSlot.delete_all
Form.delete_all
Slot.delete_all
TitleMapping.delete_all
TitleCompetencyMapping.delete_all
Competency.delete_all
Template.delete_all
LevelMapping.delete_all
Title.delete_all
Approver.delete_all
UserGroup.delete_all
Schedule.delete_all
Period.delete_all
User.delete_all
# Role.delete_all
Project.delete_all
# Company.delete_all
Group.delete_all
ProjectMember.delete_all

User.create(id: 1, email: "admin@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "admin", last_name: "admin", account: "admin", role_id: "1", company_id: 3, joined_date: rand(12).years.ago, gender: rand(2), title_id: rand(1..3)) 
User.create([
  { id: 2, email: "luanvk@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Luân", last_name: "Võ Kinh", account: "LuanVK", role_id: "1", company_id: 3, joined_date: DateTime.parse("2006-01-10"), gender: true },
  { id: 3, email: "phongbq@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phong", last_name: "Bùi Quang", account: "PhongBQ", company_id: 3, joined_date: DateTime.parse("2013-09-09"), gender: true },
  { id: 4, email: "phuonghq@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phương", last_name: "Hồ Quế", account: "PhuongHQ", company_id: 3, joined_date: DateTime.parse("2010-03-15"), gender: false },
  { id: 5, email: "thuytt1@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thùy", last_name: "Trần Thị", account: "ThuyTT1", company_id: 3, joined_date: DateTime.parse("2014-07-21"), gender: false },
  { id: 6, email: "toanpq@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Toán", last_name: "Phùng Quốc", account: "ToanPQ", role_id: "1", company_id: 3, joined_date: DateTime.parse("2014-09-20"), gender: true },
  { id: 7, email: "tuanhna@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tuấn", last_name: "Huỳnh Ngọc Anh", account: "TuanHNA", role_id: "12", company_id: 3, joined_date: DateTime.parse("2015-01-19"), gender: true },
  { id: 8, email: "nhannt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhân", last_name: "Nguyễn Toàn", account: "NhanNT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2015-03-02"), gender: true },
  { id: 9, email: "thangnt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thắng", last_name: "Nguyễn Tất", account: "ThangNT", company_id: 3, joined_date: DateTime.parse("2015-04-01"), gender: true },
  { id: 10, email: "dungpt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Dung", last_name: "Phạm Thu", account: "DungPT", company_id: 3, joined_date: DateTime.parse("2016-05-04"), gender: false },
  { id: 11, email: "trucdtt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trúc", last_name: "Dư Thị Thanh", account: "TrucDTT", company_id: 3, joined_date: DateTime.parse("2016-05-16"), gender: false },
  { id: 12, email: "thihq@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thi", last_name: "Hà Quang", account: "ThiHQ", role_id: "1", company_id: 3, joined_date: DateTime.parse("2017-06-05"), gender: true },
  { id: 13, email: "phatnt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phát", last_name: "Nguyễn Tấn", account: "PhatNT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2017-08-01"), gender: true },
  { id: 14, email: "phuocnhh@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phước", last_name: "Nguyễn Hồ Hải", account: "PhuongNHH", role_id: "1", company_id: 3, joined_date: DateTime.parse("2018-05-21"), gender: true },
  { id: 15, email: "toanpd@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Toàn", last_name: "Phạm Đức", account: "ToanPD", role_id: "1", company_id: 3, joined_date: DateTime.parse("2018-07-09"), gender: true },
  { id: 16, email: "daonth@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Đào", last_name: "Nguyễn Thị Hồng", account: "DaoNTH", company_id: 3, joined_date: DateTime.parse("2018-09-04"), gender: false },
  { id: 17, email: "hienltv@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hiển", last_name: "Lê Tấn Vinh", account: "HienLTV", role_id: "1", company_id: 3, joined_date: DateTime.parse("2018-11-08"), gender: true },
  { id: 18, email: "hoabta@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hoa", last_name: "Bùi Thị Ánh", account: "HoaBTA", role_id: "1", company_id: 3, joined_date: DateTime.parse("2018-11-08"), gender: false },
  { id: 19, email: "danhth@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Danh", last_name: "Thái Hoàng", account: "DanhTH", company_id: 3, joined_date: DateTime.parse("2018-11-26"), gender: true },
  { id: 20, email: "thintm@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thi", last_name: "Nguyễn Thị Minh", account: "ThiNTM", role_id: "1", company_id: 3, joined_date: DateTime.parse("2018-11-26"), gender: false },
  { id: 21, email: "nhannh@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhân", last_name: "Nguyễn Hữu", account: "NhanNH", role_id: "1", company_id: 3, joined_date: DateTime.parse("2018-11-26"), gender: true },
  { id: 22, email: "lydt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lý", last_name: "Đỗ Thị", account: "LyDT", company_id: 3, joined_date: DateTime.parse("2019-03-18"), gender: false },
  { id: 23, email: "phupt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phú", last_name: "Phạm Thanh", account: "PhuPT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-04-08"), gender: true },
  { id: 24, email: "ngocttb@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ngọc", last_name: "Trần Thị Bảo", account: "NgocTTB", company_id: 3, joined_date: DateTime.parse("2019-04-16"), gender: false },
  { id: 25, email: "locts@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lộc", last_name: "Trần Song", account: "LocTS", company_id: 3, joined_date: DateTime.parse("2017-10-09"), gender: true },
  { id: 26, email: "anhpth@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Phạm Thị Huế", account: "AnhPTH", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-05-13"), gender: false },
  { id: 27, email: "longnkh@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Long", last_name: "Nguyễn Khoa Hải", account: "LongNKH", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-07-08"), gender: true },
  { id: 28, email: "congnt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Công", last_name: "Nguyễn Thành", account: "CongNT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-08-19"), gender: true },
  { id: 29, email: "nhutnh@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhựt", last_name: "Nguyễn Hồng", account: "NhutNH", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-08-26"), gender: true },
  { id: 30, email: "anhndt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Nguyễn Đình Tân", account: "AnhNDT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-08-26"), gender: true },
  { id: 31, email: "dunglt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Dũng", last_name: "Lê Thanh", account: "DungLT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-07-15"), gender: true },
  { id: 32, email: "duyta@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Duy", last_name: "Trần Anh", account: "DuyTA", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-08-06"), gender: true },
  { id: 33, email: "quangpd@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Quang", last_name: "Phạm Duy", account: "QuangPD", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-09-16"), gender: true },
  { id: 34, email: "khanhnd@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Khánh", last_name: "Nguyễn Duy", account: "KhanhND", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-09-16"), gender: true },
  { id: 35, email: "tuannd@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tuấn", last_name: "Nguyễn Đức", account: "TuanND", role_id: "1", company_id: 3, joined_date: DateTime.parse("2019-10-15"), gender: true },
  { id: 36, email: "vinhpt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vinh", last_name: "Phạm Tấn", account: "VinhPT", role_id: "1", company_id: 3, joined_date: DateTime.parse("2020-05-04"), gender: true },
  { id: 37, email: "huongptb@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hường", last_name: "Phạm Thị Bích", account: "HuongPTB", company_id: 3, joined_date: DateTime.parse("2020-06-08"), gender: false },
  { id: 38, email: "sangnm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Sang", last_name: "Nguyễn Minh", account: "SangNM", company_id: 2, joined_date: DateTime.parse("2006-01-10"), gender: true },
  { id: 39, email: "tuyenhtk@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tuyền", last_name: "Hồ Thị Kim", account: "TuyenHTK", role_id: "4", company_id: 2, joined_date: DateTime.parse("2006-11-09"), gender: false },
  { id: 40, email: "tientqh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tiền", last_name: "Trần Quang Hoàng", account: "TienTQH", role_id: "5", company_id: 2, joined_date: DateTime.parse("2010-03-11"), gender: false },
  { id: 41, email: "hylh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hy", last_name: "Lê Hữu", account: "HyLH", role_id: "8", company_id: 2, joined_date: DateTime.parse("2011-04-01"), gender: true },
  { id: 42, email: "huyenttn@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huyền", last_name: "Trương Thị Ngọc", account: "HuyenTTN", role_id: "5", company_id: 2, joined_date: DateTime.parse("2011-09-22"), gender: false },
  { id: 43, email: "tamlm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tâm", last_name: "Lê Minh", account: "TamLM", role_id: "9", company_id: 2, joined_date: DateTime.parse("2011-10-03"), gender: true },
  { id: 44, email: "thuyht@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thủy", last_name: "Hoàng Thị", account: "ThuyHT", role_id: "8", company_id: 2, joined_date: DateTime.parse("2012-02-27"), gender: false },
  { id: 45, email: "dungnt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Dũng", last_name: "Nguyễn Trung", account: "DungNT", role_id: "8", company_id: 2, joined_date: DateTime.parse("2012-03-01"), gender: true },
  { id: 46, email: "ducnh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Đức", last_name: "Nguyễn Hồng", account: "DucNH", role_id: "4", company_id: 2, joined_date: DateTime.parse("2013-01-08"), gender: true },
  { id: 47, email: "tinbk@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tín", last_name: "Bùi Khắc", account: "TinBK", role_id: "8", company_id: 2, joined_date: DateTime.parse("2013-03-26"), gender: true },
  { id: 48, email: "linhptm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Linh", last_name: "Phạm Thị Mỹ", account: "LinhPTM", role_id: "8", company_id: 2, joined_date: DateTime.parse("2013-05-20"), gender: false },
  { id: 49, email: "lypt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lý", last_name: "Phùng Thị", account: "LyPT", role_id: "3", company_id: 2, joined_date: DateTime.parse("2013-10-14"), gender: false },
  { id: 50, email: "manhdt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Mạnh", last_name: "Đặng Thế", account: "ManhDT", role_id: "9", company_id: 2, joined_date: DateTime.parse("2013-11-20"), gender: true },
  { id: 51, email: "chitl@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Chi", last_name: "Trương Lan", account: "ChiTL", role_id: "2", company_id: 2, joined_date: DateTime.parse("2014-08-11"), gender: false },
  { id: 52, email: "nhanh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhã", last_name: "Nguyễn Hoàng", account: "NhaNH", role_id: "1", company_id: 2, joined_date: DateTime.parse("2015-12-14"), gender: true },
  { id: 53, email: "vuvt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vũ", last_name: "Võ Trường", account: "VuVT", role_id: "7", company_id: 2, joined_date: DateTime.parse("2016-05-23"), gender: true },
  { id: 54, email: "tuyenntt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tuyền", last_name: "Nguyễn Thụy Thanh", account: "TuyenNTT", company_id: 2, joined_date: DateTime.parse("2017-03-01"), gender: false },
  { id: 55, email: "dongnc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Đông", last_name: "Nguyễn Chính", account: "DongNC", role_id: "1", company_id: 2, joined_date: DateTime.parse("2017-04-27"), gender: true },
  { id: 56, email: "trangptm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trang", last_name: "Phạm Trần Minh", account: "TrangPTM", company_id: 2, joined_date: DateTime.parse("2017-05-15"), gender: false },
  { id: 57, email: "anhntm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Nguyễn Thị Minh", account: "AnhNTM", company_id: 2, joined_date: DateTime.parse("2017-07-17"), gender: false },
  { id: 58, email: "khoanna@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Khoa", last_name: "Nguyễn Ngọc Anh", account: "KhoaNNA", role_id: "7", company_id: 2, joined_date: DateTime.parse("2017-09-18"), gender: true },
  { id: 59, email: "khanhnlc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Khanh", last_name: "Nguyễn Lê Công", account: "KhanhNLC", role_id: "8", company_id: 2, joined_date: DateTime.parse("2017-10-02"), gender: true },
  { id: 60, email: "tienlt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tiền", last_name: "Lý Thủy", account: "TienLT", role_id: "1", company_id: 2, joined_date: DateTime.parse("2017-11-06"), gender: true },
  { id: 61, email: "nhankt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhân", last_name: "Khưu Trọng", account: "NhanKT", role_id: "3", company_id: 2, joined_date: DateTime.parse("2017-12-25"), gender: true },
  { id: 62, email: "hienhm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hiền", last_name: "Huỳnh Minh", account: "HienHM", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-01-08"), gender: true },
  { id: 63, email: "anhlt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Lê Tuấn", account: "AnhLT", role_id: "8", company_id: 2, joined_date: DateTime.parse("2018-01-22"), gender: true },
  { id: 64, email: "kimtx@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Kim", last_name: "Trương Xuân", account: "KimTX", role_id: "3", company_id: 2, joined_date: DateTime.parse("2018-04-16"), gender: false },
  { id: 65, email: "ninhnt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ninh", last_name: "Nguyễn Thị", account: "NinhNT", role_id: "3", company_id: 2, joined_date: DateTime.parse("2018-05-02"), gender: false },
  { id: 66, email: "danhnc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Danh", last_name: "Nguyễn Công", account: "DanhNC", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-05-02"), gender: true },
  { id: 67, email: "thoph@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thọ", last_name: "Phan Hoàng", account: "ThoPH", role_id: "5", company_id: 2, joined_date: DateTime.parse("2018-05-14"), gender: true },
  { id: 68, email: "thuanpp@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thuận", last_name: "Phan Phát", account: "ThuanPP", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-05-28"), gender: true },
  { id: 69, email: "trungbn@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trung", last_name: "Bùi Nam", account: "TrungBN", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-07-09"), gender: true },
  { id: 70, email: "vinhnt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vinh", last_name: "Nguyễn Thế", account: "VinhNT", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-07-09"), gender: true },
  { id: 71, email: "nhanlc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhân", last_name: "Lâm Cầm", account: "NhanLC", company_id: 2, joined_date: DateTime.parse("2018-07-09"), gender: true },
  { id: 72, email: "duybc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Duy", last_name: "Bùi Công", account: "DuyBC", role_id: "6", company_id: 2, joined_date: DateTime.parse("2018-07-09"), gender: true },
  { id: 73, email: "kieunt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Kiều", last_name: "Nguyễn Tiểu", account: "KieuNT", role_id: "8", company_id: 2, joined_date: DateTime.parse("2018-08-20"), gender: false },
  { id: 74, email: "luongtv@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lượng", last_name: "Trần Văn", account: "LuongTV", role_id: "2", company_id: 2, joined_date: DateTime.parse("2018-09-24"), gender: true },
  { id: 75, email: "nhandta@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhân", last_name: "Dương Thị Ái", account: "NhanDTA", company_id: 2, joined_date: DateTime.parse("2018-09-24"), gender: false },
  { id: 76, email: "dungnha@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Dũng", last_name: "Nguyễn Hùng Anh", account: "DungNHA", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-10-08"), gender: true },
  { id: 77, email: "vinhnh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vinh", last_name: "Nguyễn Hửu", account: "VinhNH", role_id: "3", company_id: 2, joined_date: DateTime.parse("2018-10-10"), gender: true },
  { id: 78, email: "trungpc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trung", last_name: "Phan Chí", account: "TrungPC", role_id: "1", company_id: 2, joined_date: DateTime.parse("2018-11-05"), gender: true },
  { id: 79, email: "tamvt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tâm", last_name: "Vũ Thiện", account: "TamVT", role_id: "9", company_id: 2, joined_date: DateTime.parse("2019-03-18"), gender: true },
  { id: 80, email: "trinhtth@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trinh", last_name: "Trương Thị Hồng", account: "TrinhTTH", role_id: "8", company_id: 2, joined_date: DateTime.parse("2019-03-26"), gender: false },
  { id: 81, email: "haptt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hà", last_name: "Phạm Thị Thu", account: "HaPTT", role_id: "2", company_id: 2, joined_date: DateTime.parse("2019-04-15"), gender: false },
  { id: 82, email: "mylth@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Mỹ", last_name: "Lưu Thị Hoàng", account: "MyLTH", role_id: "9", company_id: 2, joined_date: DateTime.parse("2019-04-15"), gender: false },
  { id: 83, email: "phuongttb@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phượng", last_name: "Trần Thị Bích", account: "PhuongTTB", role_id: "3", company_id: 2, joined_date: DateTime.parse("2019-05-20"), gender: false },
  { id: 84, email: "phuongltm@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phương", last_name: "Lê Thị Mai", account: "PhuongLTM", role_id: "2", company_id: 2, joined_date: DateTime.parse("2019-05-20"), gender: false },
  { id: 85, email: "songdt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Song", last_name: "Dương Thanh", account: "SongDT", role_id: "1", company_id: 2, joined_date: DateTime.parse("2019-06-03"), gender: true },
  { id: 86, email: "lamtq@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lâm", last_name: "Trần Quốc", account: "LamTQ", role_id: "1", company_id: 2, joined_date: DateTime.parse("2014-11-24"), gender: true },
  { id: 87, email: "huyenntt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huyền", last_name: "Nguyễn Thị Thu", account: "HuyenNTT", company_id: 2, joined_date: DateTime.parse("2019-07-15"), gender: false },
  { id: 88, email: "tiennc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tiên", last_name: "Nguyễn Thị Cẩm", account: "TienNTC", role_id: "3", company_id: 2, joined_date: DateTime.parse("2019-10-08"), gender: false },
  { id: 89, email: "thuannt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thuấn", last_name: "Nguyễn Thiện", account: "ThuanNT", role_id: "3", company_id: 2, joined_date: DateTime.parse("2019-10-08"), gender: true },
  { id: 90, email: "kienlv@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Kiên", last_name: "Lê Văn", account: "KienLV", role_id: "6", company_id: 2, joined_date: DateTime.parse("2019-08-19"), gender: true },
  { id: 91, email: "tamhc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tâm", last_name: "Huỳnh Chí", account: "TamHC", company_id: 2, joined_date: DateTime.parse("2019-08-26"), gender: true },
  { id: 92, email: "tienntk@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tiên", last_name: "Nguyễn Thị Khánh", account: "TienNTK", role_id: "8", company_id: 2, joined_date: DateTime.parse("2019-09-10"), gender: false },
  { id: 93, email: "nganntn@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ngân", last_name: "Nguyễn Thị Ngọc", account: "NganNTN", role_id: "8", company_id: 2, joined_date: DateTime.parse("2019-10-01"), gender: false },
  { id: 94, email: "tralh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trà", last_name: "Lưu Hương", account: "TraLH", company_id: 2, joined_date: DateTime.parse("2019-10-11"), gender: false },
  { id: 95, email: "trinhnpt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trinh", last_name: "Nguyễn Phan Thảo", account: "TrinhNPT", role_id: "13", company_id: 2, joined_date: DateTime.parse("2019-10-11"), gender: false },
  { id: 96, email: "phuongpth@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phương", last_name: "Phạm Thị Hồng", account: "PhuongPTH", role_id: "13", company_id: 2, joined_date: DateTime.parse("2019-10-11"), gender: false },
  { id: 97, email: "yenntp@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Yến", last_name: "Nguyễn Thị Phi", account: "YenNTP", role_id: "8", company_id: 2, joined_date: DateTime.parse("2019-09-11"), gender: false },
  { id: 98, email: "huyennt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huyền", last_name: "Nguyễn Thị", account: "HuyenNT", role_id: "2", company_id: 2, joined_date: DateTime.parse("2019-11-04"), gender: false },
  { id: 99, email: "lienpt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Liên", last_name: "Phan Thị", account: "LienPT", role_id: "3", company_id: 2, joined_date: DateTime.parse("2019-12-02"), gender: false },
  { id: 100, email: "khoanda@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Khoa", last_name: "Nguyễn Đăng Anh", account: "KhoaNDA", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-02-03"), gender: true },
  { id: 101, email: "tuanpl@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tuấn", last_name: "Phạm Lê", account: "TuanPL", role_id: "3", company_id: 2, joined_date: DateTime.parse("2020-02-17"), gender: true },
  { id: 102, email: "huannt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huân", last_name: "Nguyễn Trọng", account: "HuanNT", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-01-02"), gender: true },
  { id: 103, email: "phungnv@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phụng", last_name: "Nguyễn Văn", account: "PhungNV", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-01-02"), gender: true },
  { id: 104, email: "huylc@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huy", last_name: "Lương Chí", account: "HuyLC", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-03-16"), gender: true },
  { id: 105, email: "thanhntt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thanh", last_name: "Nguyễn Thị Tú", account: "ThanhNTT", role_id: "13", company_id: 2, joined_date: DateTime.parse("2020-05-04"), gender: false },
  { id: 106, email: "ngocph@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ngọc", last_name: "Phạm Hữu", account: "NgocPH", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: true },
  { id: 107, email: "hoanpt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hoan", last_name: "Phùng Thế", account: "HoanPT", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: true },
  { id: 108, email: "vinhmx@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vinh", last_name: "Mai Xuân", account: "VinhMX", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: true },
  { id: 109, email: "hieuam@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hiếu", last_name: "Ao Minh", account: "HieuAM", role_id: "6", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: true },
  { id: 110, email: "phuctnh@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phúc", last_name: "Trần Nguyễn Hoàng", account: "PhucTNH", role_id: "1", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: true },
  { id: 111, email: "hiendt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hiền", last_name: "Đinh Thúy", account: "HienDT", role_id: "3", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: false },
  { id: 112, email: "phuongchn@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phượng", last_name: "Cao Hoàng Ngọc", account: "PhuongCHN", role_id: "3", company_id: 2, joined_date: DateTime.parse("2020-05-18"), gender: false },
  { id: 113, email: "quynhnnn@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Quỳnh", last_name: "Nguyễn Ngọc Như", account: "QuynhNNN", role_id: "2", company_id: 2, joined_date: DateTime.parse("2020-05-25"), gender: false },
  { id: 114, email: "yennt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Yến", last_name: "Nguyễn Thiên", account: "YenNT", role_id: "8", company_id: 2, joined_date: DateTime.parse("2020-06-01"), gender: false },
  { id: 115, email: "thaont@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thảo", last_name: "Nguyễn Thị", account: "ThaoNT", role_id: "8", company_id: 2, joined_date: DateTime.parse("2020-06-01"), gender: false },
  { id: 116, email: "anhpt@bestarion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Phạm Thu", account: "AnhPT", company_id: 2, joined_date: DateTime.parse("2020-06-15"), gender: false },
  { id: 117, email: "tiennnt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tiên", last_name: "Nguyễn Ngọc Thủy", account: "TienNNT", company_id: 2, joined_date: DateTime.parse("2019-08-21"), gender: false },
  { id: 118, email: "dieultt@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Diệu", last_name: "Lê Thị Thu", account: "DieuLTT", company_id: 2, joined_date: DateTime.parse("2018-07-02"), gender: false },
  { id: 119, email: "hoangnn@larion.com", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hoàng", last_name: "Ngô Ngọc", account: "HoangNN", company_id: 2, joined_date: DateTime.parse("2017-03-01"), gender: true },
  { id: 120, email: "anhptm@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Phạm Thị Mai", account: "AnhPTM", role_id: "2", company_id: 4, joined_date: DateTime.parse("2010-04-01"), gender: false },
  { id: 121, email: "anhtk@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ánh", last_name: "Trần Kim", account: "AnhTK", role_id: "8", company_id: 4, joined_date: DateTime.parse("2012-01-03"), gender: false },
  { id: 122, email: "hienptt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hiền", last_name: "Phạm Thị Thu", account: "HienPTT", role_id: "3", company_id: 4, joined_date: DateTime.parse("2013-09-09"), gender: false },
  { id: 123, email: "linhht@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Linh", last_name: "Hồ Tuấn", account: "LinhHT", role_id: "1", company_id: 4, joined_date: DateTime.parse("2017-10-02"), gender: true },
  { id: 124, email: "nhutth@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhựt", last_name: "Tạ Hoàng", account: "NhutTH", role_id: "1", company_id: 4, joined_date: DateTime.parse("2017-10-16"), gender: true },
  { id: 125, email: "khoahk@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Khoa", last_name: "Huỳnh Kim", account: "KhoaHK", role_id: "2", company_id: 4, joined_date: DateTime.parse("2017-11-06"), gender: false },
  { id: 126, email: "lyth@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lý", last_name: "Trần Hải", account: "LyTH", company_id: 4, joined_date: DateTime.parse("2017-12-20"), gender: true },
  { id: 127, email: "xuanttt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Xuân", last_name: "Trần Thị Thanh", account: "XuanTTT", role_id: "3", company_id: 4, joined_date: DateTime.parse("2018-04-16"), gender: false },
  { id: 128, email: "vuongpntt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vương", last_name: "Phạm Nguyễn Thụy Thiên", account: "VuongPNTT", company_id: 4, joined_date: DateTime.parse("2018-04-16"), gender: false },
  { id: 129, email: "hantt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hà", last_name: "Nguyễn Thị Thúy", account: "HaNTT", company_id: 4, joined_date: DateTime.parse("2018-05-14"), gender: false },
  { id: 130, email: "baong@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Bảo", last_name: "Ngô Gia", account: "BaoNG", role_id: "2", company_id: 4, joined_date: DateTime.parse("2018-07-17"), gender: true },
  { id: 131, email: "cuongpc@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Cương", last_name: "Phạm Công", account: "CuongPC", company_id: 4, joined_date: DateTime.parse("2018-07-23"), gender: true },
  { id: 132, email: "vint@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vi", last_name: "Nguyễn Tường", account: "ViNT", role_id: "6", company_id: 4, joined_date: DateTime.parse("2018-08-27"), gender: true },
  { id: 133, email: "ngantt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nga", last_name: "Nguyễn Thị Thúy", account: "NganTT", role_id: "2", company_id: 4, joined_date: DateTime.parse("2018-09-10"), gender: false },
  { id: 134, email: "hungvm@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hùng", last_name: "Vũ Mạnh", account: "HungVM", company_id: 4, joined_date: DateTime.parse("2018-10-01"), gender: true },
  { id: 135, email: "thuynt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thủy", last_name: "Nguyễn Thu", account: "ThuyNT", company_id: 4, joined_date: DateTime.parse("2019-02-18"), gender: false },
  { id: 136, email: "khoada@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Khoa", last_name: "Đào Anh", account: "KhoaDA", role_id: "1", company_id: 4, joined_date: DateTime.parse("2019-03-18"), gender: true },
  { id: 137, email: "phuongth@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phượng", last_name: "Từ Hồng", account: "PhuongTH", role_id: "3", company_id: 4, joined_date: DateTime.parse("2019-03-18"), gender: false },
  { id: 138, email: "anhnck@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Nguyễn Cao Kiều", account: "AnhNCK", role_id: "9", company_id: 4, joined_date: DateTime.parse("2019-03-18"), gender: false },
  { id: 139, email: "quynhlm@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Quỳnh", last_name: "Lâm Mỹ", account: "QuynhLM", role_id: "9", company_id: 4, joined_date: DateTime.parse("2019-03-18"), gender: false },
  { id: 140, email: "phatlv@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phát", last_name: "Lê Vũ", account: "PhatLV", role_id: "1", company_id: 4, joined_date: DateTime.parse("2019-04-03"), gender: true },
  { id: 141, email: "phuongpt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Phương", last_name: "Phạm Thành", account: "PhuongPT", role_id: "1", company_id: 4, joined_date: DateTime.parse("2019-04-08"), gender: true },
  { id: 142, email: "chautnk@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Châu", last_name: "Trương Ngọc Kim", account: "ChauTNK", role_id: "3", company_id: 4, joined_date: DateTime.parse("2019-04-08"), gender: false },
  { id: 143, email: "hiepnn@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hiệp", last_name: "Nguyễn Ngọc", account: "HiepNN", role_id: "4", company_id: 4, joined_date: DateTime.parse("2019-04-22"), gender: true },
  { id: 144, email: "thunha@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thư", last_name: "Nguyễn Hồ Anh", account: "ThuNHA", role_id: "2", company_id: 4, joined_date: DateTime.parse("2019-08-01"), gender: false },
  { id: 145, email: "huynhph@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huynh", last_name: "Phạm Hoàng", account: "HuynhPH", role_id: "1", company_id: 4, joined_date: DateTime.parse("2019-05-02"), gender: true },
  { id: 146, email: "huynh@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huy", last_name: "Nguyễn Hoàng", account: "HuyNH", role_id: "1", company_id: 4, joined_date: DateTime.parse("2019-05-02"), gender: true },
  { id: 147, email: "huelt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huế", last_name: "Lê Thị", account: "HueLT", company_id: 4, joined_date: DateTime.parse("2019-05-13"), gender: false },
  { id: 148, email: "hoanglnh@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Hoàng", last_name: "Lê Nguyễn Huy", account: "HoangLNH", role_id: "6", company_id: 4, joined_date: DateTime.parse("2019-05-13"), gender: true },
  { id: 149, email: "anhvtn@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ánh", last_name: "Võ Thị Ngọc", account: "AnhVTN", company_id: 4, joined_date: DateTime.parse("2019-05-20"), gender: false },
  { id: 150, email: "trangdmk@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trang", last_name: "Đinh Minh Kiều", account: "TrangDMK", company_id: 4, joined_date: DateTime.parse("2019-06-03"), gender: false },
  { id: 151, email: "ngocdlh@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Ngọc", last_name: "Đào Lê Hồng", account: "NgocDLH", company_id: 4, joined_date: DateTime.parse("2019-06-03"), gender: false },
  { id: 152, email: "nhanhdt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhanh", last_name: "Đặng Thị", account: "NhanHDT", company_id: 4, joined_date: DateTime.parse("2019-07-15"), gender: false },
  { id: 153, email: "nhanv@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhã", last_name: "Nguyễn Vân", account: "NhaNV", company_id: 4, joined_date: DateTime.parse("2019-08-19"), gender: false },
  { id: 154, email: "duynv@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Duy", last_name: "Nguyễn Văn", account: "DuyNV", role_id: "9", company_id: 4, joined_date: DateTime.parse("2019-10-01"), gender: true },
  { id: 155, email: "huynvn@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Huy", last_name: "Nguyễn Vũ Nhật", account: "HuyNVN", role_id: "1", company_id: 4, joined_date: DateTime.parse("2020-05-04"), gender: true },
  { id: 156, email: "trangntt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Trang", last_name: "Nguyễn Thị Thu", account: "TrangNTT", company_id: 4, joined_date: DateTime.parse("2020-06-01"), gender: false },
  { id: 157, email: "tungtt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Tùng", last_name: "Trương Thanh", account: "TungTT", role_id: "2", company_id: 4, joined_date: DateTime.parse("2020-06-08"), gender: true },
  { id: 158, email: "cuongnm@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Cường", last_name: "Nguyễn Minh", account: "CuongNM", company_id: 4, joined_date: DateTime.parse("2013-11-01"), gender: true },
  { id: 159, email: "anhlt1@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Anh", last_name: "Lê Tú", account: "AnhLT1", role_id: "1", company_id: 4, joined_date: DateTime.parse("2018-11-07"), gender: true },
  { id: 160, email: "thuytt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thúy", last_name: "Trương Thị", account: "ThuyTT", company_id: 4, joined_date: DateTime.parse("2013-10-28"), gender: false },
  { id: 161, email: "vandth@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vân", last_name: "Đoàn Thị Hồng", account: "VanDTH", company_id: 4, joined_date: DateTime.parse("2015-09-07"), gender: false },
  { id: 162, email: "duytnm@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Duy", last_name: "Trần Ngọc Minh", account: "DuyTNM", company_id: 4, joined_date: DateTime.parse("2019-04-15"), gender: true },
  { id: 163, email: "vupt@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Vũ", last_name: "Phạm Tuấn", account: "VuPT", role_id: "2", company_id: 4, joined_date: DateTime.parse("2020-06-24"), gender: true },
  { id: 164, email: "duyenbnb@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Duyên", last_name: "Bùi Nguyên Bảo", account: "DuyenBNB", company_id: 4, joined_date: DateTime.parse("2020-06-25"), gender: false },
  { id: 165, email: "thangnd@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Thăng", last_name: "Nguyễn Đức", account: "ThangND", role_id: "1", company_id: 4, joined_date: DateTime.parse("2020-07-01"), gender: true },
  { id: 166, email: "lyvtb@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Lý", last_name: "Võ Thị Bảo", account: "LyVTB", company_id: 4, joined_date: DateTime.parse("2020-07-01"), gender: false },
  { id: 167, email: "nhungnth@atalink.vn", password: "123QWEasd", password_confirmation: "123QWEasd", first_name: "Nhung", last_name: "Nguyễn Thị Hồng", account: "NhungNTH", company_id: 4, joined_date: DateTime.parse("2020-07-06"), gender: false },
])

Project.create([
  { id: 1, name: "Mars", company_id: 3 },
  { id: 2, name: "IT", company_id: 3 },
  { id: 3, name: "FA", company_id: 3 },
  { id: 4, name: "Admin", company_id: 3 },
  { id: 5, name: "QM", company_id: 3 },
  { id: 6, name: "HR", company_id: 3 },
  { id: 7, name: "SDD2", company_id: 3 },
  { id: 8, name: "MSS", company_id: 2 },
  { id: 9, name: "CLS", company_id: 2 },
  { id: 10, name: "MIMS", company_id: 2 },
  { id: 11, name: "Integration Testing", company_id: 2 },
  { id: 12, name: "HUB", company_id: 2 },
  { id: 13, name: "QBO", company_id: 2 },
  { id: 14, name: "SCS", company_id: 2 },
  { id: 15, name: "CDS", company_id: 2 },
  { id: 16, name: "SnM", company_id: 2 },
  { id: 17, name: "Green Field", company_id: 4 },
  { id: 18, name: "Hot Sea", company_id: 4 },
  { id: 19, name: "Blue Sky", company_id: 4 },
  { id: 20, name: "CS", company_id: 4 },
])

ProjectMember.create([
  { id: 1, user_id: 2, project_id: 1 },
  { id: 2, user_id: 3, project_id: 2 },
  { id: 3, user_id: 4, project_id: 3 },
  { id: 4, user_id: 5, project_id: 4 },
  { id: 5, user_id: 6, project_id: 1 },
  { id: 6, user_id: 7, project_id: 3 },
  { id: 7, user_id: 8, project_id: 1 },
  { id: 8, user_id: 9, project_id: 2 },
  { id: 9, user_id: 10, project_id: 4 },
  { id: 10, user_id: 11, project_id: 5 },
  { id: 11, user_id: 12, project_id: 1 },
  { id: 12, user_id: 13, project_id: 1 },
  { id: 13, user_id: 14, project_id: 1 },
  { id: 14, user_id: 15, project_id: 1 },
  { id: 15, user_id: 16, project_id: 4 },
  { id: 16, user_id: 17, project_id: 1 },
  { id: 17, user_id: 18, project_id: 1 },
  { id: 18, user_id: 19, project_id: 1 },
  { id: 19, user_id: 20, project_id: 1 },
  { id: 20, user_id: 21, project_id: 1 },
  { id: 21, user_id: 22, project_id: 6 },
  { id: 22, user_id: 23, project_id: 1 },
  { id: 23, user_id: 24, project_id: 6 },
  { id: 24, user_id: 25, project_id: 7 },
  { id: 25, user_id: 26, project_id: 1 },
  { id: 26, user_id: 27, project_id: 1 },
  { id: 27, user_id: 28, project_id: 1 },
  { id: 28, user_id: 29, project_id: 1 },
  { id: 29, user_id: 30, project_id: 1 },
  { id: 30, user_id: 31, project_id: 1 },
  { id: 31, user_id: 32, project_id: 1 },
  { id: 32, user_id: 33, project_id: 1 },
  { id: 33, user_id: 34, project_id: 1 },
  { id: 34, user_id: 35, project_id: 1 },
  { id: 35, user_id: 36, project_id: 1 },
  { id: 36, user_id: 37, project_id: 6 },
  { id: 37, user_id: 38, project_id: 8 },
  { id: 38, user_id: 39, project_id: 9 },
  { id: 39, user_id: 40, project_id: 8 },
  { id: 40, user_id: 41, project_id: 9 },
  { id: 41, user_id: 42, project_id: 8 },
  { id: 42, user_id: 43, project_id: 9 },
  { id: 43, user_id: 44, project_id: 9 },
  { id: 44, user_id: 45, project_id: 9 },
  { id: 45, user_id: 46, project_id: 8 },
  { id: 46, user_id: 47, project_id: 9 },
  { id: 47, user_id: 48, project_id: 9 },
  { id: 48, user_id: 49, project_id: 8 },
  { id: 49, user_id: 50, project_id: 9 },
  { id: 50, user_id: 51, project_id: 8 },
  { id: 51, user_id: 52, project_id: 8 },
  { id: 52, user_id: 53, project_id: 8 },
  { id: 53, user_id: 54, project_id: 9 },
  { id: 54, user_id: 55, project_id: 8 },
  { id: 55, user_id: 56, project_id: 9 },
  { id: 56, user_id: 57, project_id: 9 },
  { id: 57, user_id: 58, project_id: 8 },
  { id: 58, user_id: 59, project_id: 9 },
  { id: 59, user_id: 60, project_id: 8 },
  { id: 60, user_id: 61, project_id: 8 },
  { id: 61, user_id: 62, project_id: 10 },
  { id: 62, user_id: 63, project_id: 9 },
  { id: 63, user_id: 64, project_id: 11 },
  { id: 64, user_id: 65, project_id: 11 },
  { id: 65, user_id: 66, project_id: 8 },
  { id: 66, user_id: 67, project_id: 12 },
  { id: 67, user_id: 68, project_id: 12 },
  { id: 68, user_id: 69, project_id: 10 },
  { id: 69, user_id: 70, project_id: 8 },
  { id: 70, user_id: 71, project_id: 8 },
  { id: 71, user_id: 72, project_id: 8 },
  { id: 72, user_id: 73, project_id: 9 },
  { id: 73, user_id: 74, project_id: 8 },
  { id: 74, user_id: 75, project_id: 9 },
  { id: 75, user_id: 76, project_id: 12 },
  { id: 76, user_id: 77, project_id: 11 },
  { id: 77, user_id: 78, project_id: 12 },
  { id: 78, user_id: 79, project_id: 9 },
  { id: 79, user_id: 80, project_id: 9 },
  { id: 80, user_id: 81, project_id: 10 },
  { id: 81, user_id: 82, project_id: 9 },
  { id: 82, user_id: 83, project_id: 11 },
  { id: 83, user_id: 84, project_id: 10 },
  { id: 84, user_id: 85, project_id: 12 },
  { id: 85, user_id: 86, project_id: 10 },
  { id: 86, user_id: 87, project_id: 9 },
  { id: 87, user_id: 88, project_id: 10 },
  { id: 88, user_id: 89, project_id: 8 },
  { id: 89, user_id: 90, project_id: 8 },
  { id: 90, user_id: 91, project_id: 8 },
  { id: 91, user_id: 92, project_id: 9 },
  { id: 92, user_id: 93, project_id: 9 },
  { id: 93, user_id: 94, project_id: 13 },
  { id: 94, user_id: 95, project_id: 13 },
  { id: 95, user_id: 96, project_id: 13 },
  { id: 96, user_id: 97, project_id: 9 },
  { id: 97, user_id: 98, project_id: 12 },
  { id: 98, user_id: 99, project_id: 8 },
  { id: 99, user_id: 100, project_id: 8 },
  { id: 100, user_id: 101, project_id: 14 },
  { id: 101, user_id: 102, project_id: 14 },
  { id: 102, user_id: 103, project_id: 15 },
  { id: 103, user_id: 104, project_id: 14 },
  { id: 104, user_id: 105, project_id: 13 },
  { id: 105, user_id: 106, project_id: 8 },
  { id: 106, user_id: 107, project_id: 15 },
  { id: 107, user_id: 108, project_id: 8 },
  { id: 108, user_id: 109, project_id: 8 },
  { id: 109, user_id: 110, project_id: 15 },
  { id: 110, user_id: 111, project_id: 14 },
  { id: 111, user_id: 112, project_id: 11 },
  { id: 112, user_id: 113, project_id: 8 },
  { id: 113, user_id: 114, project_id: 9 },
  { id: 114, user_id: 115, project_id: 9 },
  { id: 115, user_id: 116, project_id: 16 },
  { id: 116, user_id: 117, project_id: 5 },
  { id: 117, user_id: 118, project_id: 3 },
  { id: 118, user_id: 119, project_id: 2 },
  { id: 119, user_id: 120, project_id: 17 },
  { id: 120, user_id: 121, project_id: 18 },
  { id: 121, user_id: 122, project_id: 19 },
  { id: 122, user_id: 123, project_id: 19 },
  { id: 123, user_id: 124, project_id: 19 },
  { id: 124, user_id: 125, project_id: 17 },
  { id: 125, user_id: 126, project_id: 19 },
  { id: 126, user_id: 127, project_id: 19 },
  { id: 127, user_id: 128, project_id: 18 },
  { id: 128, user_id: 129, project_id: 19 },
  { id: 129, user_id: 130, project_id: 17 },
  { id: 130, user_id: 131, project_id: 19 },
  { id: 131, user_id: 132, project_id: 19 },
  { id: 132, user_id: 133, project_id: 17 },
  { id: 133, user_id: 134, project_id: 19 },
  { id: 134, user_id: 135, project_id: 16 },
  { id: 135, user_id: 136, project_id: 19 },
  { id: 136, user_id: 137, project_id: 19 },
  { id: 137, user_id: 138, project_id: 18 },
  { id: 138, user_id: 139, project_id: 18 },
  { id: 139, user_id: 140, project_id: 19 },
  { id: 140, user_id: 141, project_id: 19 },
  { id: 141, user_id: 142, project_id: 19 },
  { id: 142, user_id: 143, project_id: 19 },
  { id: 143, user_id: 144, project_id: 17 },
  { id: 144, user_id: 145, project_id: 19 },
  { id: 145, user_id: 146, project_id: 19 },
  { id: 146, user_id: 147, project_id: 16 },
  { id: 147, user_id: 148, project_id: 19 },
  { id: 148, user_id: 149, project_id: 18 },
  { id: 149, user_id: 150, project_id: 18 },
  { id: 150, user_id: 151, project_id: 16 },
  { id: 151, user_id: 152, project_id: 16 },
  { id: 152, user_id: 153, project_id: 16 },
  { id: 153, user_id: 154, project_id: 18 },
  { id: 154, user_id: 155, project_id: 19 },
  { id: 155, user_id: 156, project_id: 16 },
  { id: 156, user_id: 157, project_id: 17 },
  { id: 157, user_id: 158, project_id: 19 },
  { id: 158, user_id: 159, project_id: 19 },
  { id: 159, user_id: 160, project_id: 5 },
  { id: 160, user_id: 161, project_id: 6 },
  { id: 161, user_id: 162, project_id: 2 },
  { id: 162, user_id: 163, project_id: 17 },
  { id: 163, user_id: 164, project_id: 20 },
  { id: 164, user_id: 165, project_id: 19 },
  { id: 165, user_id: 166, project_id: 4 },
  { id: 166, user_id: 167, project_id: 16 },
])

Group.create!(id: 1, name: "Administration", description: "Administration", status: 1, privileges: "1,2,4,5,7,9,10,13,14,15,16,17,19,18,20,21,22,24")
Group.create!(id: 2, name: "BOD", description: "BOD", status: 1, privileges: "10")
Group.create!(id: 3, name: "HR", description: "HR", status: 1, privileges: "9,10,13")
Group.create!(id: 4, name: "Manager", description: "Manager", status: 1, privileges: "1")
Group.create!(id: 5, name: "Reviewer", description: "Reviewer", status: 1, privileges: "16")
Group.create!(id: 6, name: "Staff", description: "Staff", status: 1, privileges: "15,19,23")
Group.create!(id: 7, name: "PM", description: "PM", status: 1, privileges: "14,17")

UserGroup.create(group_id: 1, user_id: 1)
UserGroup.create([
  { id: 2, user_id: 2, group_id: 6 },
  { id: 3, user_id: 3, group_id: 6 },
  { id: 4, user_id: 4, group_id: 6 },
  { id: 5, user_id: 5, group_id: 6 },
  { id: 6, user_id: 6, group_id: 6 },
  { id: 7, user_id: 7, group_id: 6 },
  { id: 8, user_id: 8, group_id: 6 },
  { id: 9, user_id: 9, group_id: 6 },
  { id: 10, user_id: 10, group_id: 6 },
  { id: 11, user_id: 11, group_id: 6 },
  { id: 12, user_id: 12, group_id: 6 },
  { id: 13, user_id: 13, group_id: 6 },
  { id: 14, user_id: 14, group_id: 6 },
  { id: 15, user_id: 15, group_id: 6 },
  { id: 16, user_id: 16, group_id: 6 },
  { id: 17, user_id: 17, group_id: 6 },
  { id: 18, user_id: 18, group_id: 6 },
  { id: 19, user_id: 19, group_id: 6 },
  { id: 20, user_id: 20, group_id: 6 },
  { id: 21, user_id: 21, group_id: 6 },
  { id: 22, user_id: 22, group_id: 6 },
  { id: 23, user_id: 23, group_id: 6 },
  { id: 24, user_id: 24, group_id: 6 },
  { id: 25, user_id: 25, group_id: 6 },
  { id: 26, user_id: 26, group_id: 6 },
  { id: 27, user_id: 27, group_id: 6 },
  { id: 28, user_id: 28, group_id: 6 },
  { id: 29, user_id: 29, group_id: 6 },
  { id: 30, user_id: 30, group_id: 6 },
  { id: 31, user_id: 31, group_id: 6 },
  { id: 32, user_id: 32, group_id: 6 },
  { id: 33, user_id: 33, group_id: 6 },
  { id: 34, user_id: 34, group_id: 6 },
  { id: 35, user_id: 35, group_id: 6 },
  { id: 36, user_id: 36, group_id: 6 },
  { id: 37, user_id: 37, group_id: 6 },
  { id: 38, user_id: 38, group_id: 6 },
  { id: 39, user_id: 39, group_id: 6 },
  { id: 40, user_id: 40, group_id: 6 },
  { id: 41, user_id: 41, group_id: 6 },
  { id: 42, user_id: 42, group_id: 6 },
  { id: 43, user_id: 43, group_id: 6 },
  { id: 44, user_id: 44, group_id: 6 },
  { id: 45, user_id: 45, group_id: 6 },
  { id: 46, user_id: 46, group_id: 6 },
  { id: 47, user_id: 47, group_id: 6 },
  { id: 48, user_id: 48, group_id: 6 },
  { id: 49, user_id: 49, group_id: 6 },
  { id: 50, user_id: 50, group_id: 6 },
  { id: 51, user_id: 51, group_id: 6 },
  { id: 52, user_id: 52, group_id: 6 },
  { id: 53, user_id: 53, group_id: 6 },
  { id: 54, user_id: 54, group_id: 6 },
  { id: 55, user_id: 55, group_id: 6 },
  { id: 56, user_id: 56, group_id: 6 },
  { id: 57, user_id: 57, group_id: 6 },
  { id: 58, user_id: 58, group_id: 6 },
  { id: 59, user_id: 59, group_id: 6 },
  { id: 60, user_id: 60, group_id: 6 },
  { id: 61, user_id: 61, group_id: 6 },
  { id: 62, user_id: 62, group_id: 6 },
  { id: 63, user_id: 63, group_id: 6 },
  { id: 64, user_id: 64, group_id: 6 },
  { id: 65, user_id: 65, group_id: 6 },
  { id: 66, user_id: 66, group_id: 6 },
  { id: 67, user_id: 67, group_id: 6 },
  { id: 68, user_id: 68, group_id: 6 },
  { id: 69, user_id: 69, group_id: 6 },
  { id: 70, user_id: 70, group_id: 6 },
  { id: 71, user_id: 71, group_id: 6 },
  { id: 72, user_id: 72, group_id: 6 },
  { id: 73, user_id: 73, group_id: 6 },
  { id: 74, user_id: 74, group_id: 6 },
  { id: 75, user_id: 75, group_id: 6 },
  { id: 76, user_id: 76, group_id: 6 },
  { id: 77, user_id: 77, group_id: 6 },
  { id: 78, user_id: 78, group_id: 6 },
  { id: 79, user_id: 79, group_id: 6 },
  { id: 80, user_id: 80, group_id: 6 },
  { id: 81, user_id: 81, group_id: 6 },
  { id: 82, user_id: 82, group_id: 6 },
  { id: 83, user_id: 83, group_id: 6 },
  { id: 84, user_id: 84, group_id: 6 },
  { id: 85, user_id: 85, group_id: 6 },
  { id: 86, user_id: 86, group_id: 6 },
  { id: 87, user_id: 87, group_id: 6 },
  { id: 88, user_id: 88, group_id: 6 },
  { id: 89, user_id: 89, group_id: 6 },
  { id: 90, user_id: 90, group_id: 6 },
  { id: 91, user_id: 91, group_id: 6 },
  { id: 92, user_id: 92, group_id: 6 },
  { id: 93, user_id: 93, group_id: 6 },
  { id: 94, user_id: 94, group_id: 6 },
  { id: 95, user_id: 95, group_id: 6 },
  { id: 96, user_id: 96, group_id: 6 },
  { id: 97, user_id: 97, group_id: 6 },
  { id: 98, user_id: 98, group_id: 6 },
  { id: 99, user_id: 99, group_id: 6 },
  { id: 100, user_id: 100, group_id: 6 },
  { id: 101, user_id: 101, group_id: 6 },
  { id: 102, user_id: 102, group_id: 6 },
  { id: 103, user_id: 103, group_id: 6 },
  { id: 104, user_id: 104, group_id: 6 },
  { id: 105, user_id: 105, group_id: 6 },
  { id: 106, user_id: 106, group_id: 6 },
  { id: 107, user_id: 107, group_id: 6 },
  { id: 108, user_id: 108, group_id: 6 },
  { id: 109, user_id: 109, group_id: 6 },
  { id: 110, user_id: 110, group_id: 6 },
  { id: 111, user_id: 111, group_id: 6 },
  { id: 112, user_id: 112, group_id: 6 },
  { id: 113, user_id: 113, group_id: 6 },
  { id: 114, user_id: 114, group_id: 6 },
  { id: 115, user_id: 115, group_id: 6 },
  { id: 116, user_id: 116, group_id: 6 },
  { id: 117, user_id: 117, group_id: 6 },
  { id: 118, user_id: 118, group_id: 6 },
  { id: 119, user_id: 119, group_id: 6 },
  { id: 120, user_id: 120, group_id: 6 },
  { id: 121, user_id: 121, group_id: 6 },
  { id: 122, user_id: 122, group_id: 6 },
  { id: 123, user_id: 123, group_id: 6 },
  { id: 124, user_id: 124, group_id: 6 },
  { id: 125, user_id: 125, group_id: 6 },
  { id: 126, user_id: 126, group_id: 6 },
  { id: 127, user_id: 127, group_id: 6 },
  { id: 128, user_id: 128, group_id: 6 },
  { id: 129, user_id: 129, group_id: 6 },
  { id: 130, user_id: 130, group_id: 6 },
  { id: 131, user_id: 131, group_id: 6 },
  { id: 132, user_id: 132, group_id: 6 },
  { id: 133, user_id: 133, group_id: 6 },
  { id: 134, user_id: 134, group_id: 6 },
  { id: 135, user_id: 135, group_id: 6 },
  { id: 136, user_id: 136, group_id: 6 },
  { id: 137, user_id: 137, group_id: 6 },
  { id: 138, user_id: 138, group_id: 6 },
  { id: 139, user_id: 139, group_id: 6 },
  { id: 140, user_id: 140, group_id: 6 },
  { id: 141, user_id: 141, group_id: 6 },
  { id: 142, user_id: 142, group_id: 6 },
  { id: 143, user_id: 143, group_id: 6 },
  { id: 144, user_id: 144, group_id: 6 },
  { id: 145, user_id: 145, group_id: 6 },
  { id: 146, user_id: 146, group_id: 6 },
  { id: 147, user_id: 147, group_id: 6 },
  { id: 148, user_id: 148, group_id: 6 },
  { id: 149, user_id: 149, group_id: 6 },
  { id: 150, user_id: 150, group_id: 6 },
  { id: 151, user_id: 151, group_id: 6 },
  { id: 152, user_id: 152, group_id: 6 },
  { id: 153, user_id: 153, group_id: 6 },
  { id: 154, user_id: 154, group_id: 6 },
  { id: 155, user_id: 155, group_id: 6 },
  { id: 156, user_id: 156, group_id: 6 },
  { id: 157, user_id: 157, group_id: 6 },
  { id: 158, user_id: 158, group_id: 6 },
  { id: 159, user_id: 159, group_id: 6 },
  { id: 160, user_id: 160, group_id: 6 },
  { id: 161, user_id: 161, group_id: 6 },
  { id: 162, user_id: 162, group_id: 6 },
  { id: 163, user_id: 163, group_id: 6 },
  { id: 164, user_id: 164, group_id: 6 },
  { id: 165, user_id: 165, group_id: 6 },
  { id: 166, user_id: 166, group_id: 6 },
  { id: 167, user_id: 167, group_id: 6 },
])
